### ISSUE TITLE
Error Code 4: Internal Error (Internal error: plugin node ScatterND_12 requires 36 bytes of scratch space, but only 0 is available.

### ISSUE THREAD

**Issue by MHGL** [NVIDIA/TensorRT#1363]
## Description

I get this error while convert module to tensorrt      
- index ops at left of =
- slice ops at left of = 

## Environment

**TensorRT Version**: 8.0.0.3
**NVIDIA GPU**: GeForce GTX 1650
**NVIDIA Driver Version**: 460.80
**CUDA Version**: 11.2
**CUDNN Version**: 8.1
**Operating System**: Ubuntu20.04 LTS
**Python Version (if applicable)**: 3.8.5
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: [docker image](https://hub.docker.com/layers/gemfield/homepod/2.0-pro/images/sha256-623fa17ca0dccfc6d4586a1b514ecb12566fd618bc8735f15a6abd6cea4c7000?context=explore)   [dockerfile](https://github.com/DeepVAC/MLab/blob/main/docker/homepod/Dockerfile.pro)

## Steps To Reproduce

1. code example
```python3
import torch

# init module
class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        ...

    def forward(self, x):
        x[0] += 1
        return x

torch_model = MyModule()

# torch.onnx.export
torch.onnx.export(torch_model,
    torch.randn(1, 3, 256, 416),
    "./tmp.onnx",
    input_names=["inputs"],
    output_names=["outputs"],
    opset_version=11)

# onnx simplify
import os
import onnx
from onnxsim import simplify

onnx_file = os.path.join(os.getcwd(), "tmp.onnx")
model_op, check_ok = simplify(onnx_file, 
    check_n=3, 
    perform_optimization=True, 
    skip_fuse_bn=True,  
    skip_shape_inference=False, 
    input_shapes={"inputs": (1, 3, 256, 416)}, 
    skipped_optimizers=None, 
    )
onnx.save(model_op, "./tmp.onnx")

# onnx -> tensorrt
# !!!
# you should build tensorrt first
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
with trt.Builder(TRT_LOGGER) as builder, builder.create_network(1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
    with open(onnx_file, 'rb') as model:
        parser.parse(model.read())

    config = builder.create_builder_config()
    engine = builder.build_engine(network, config)

    with open("tmp.trt", "wb") as f:
        f.write(engine.serialize())
```

2. stack traces
```python3
Checking 0/3...
Checking 1/3...
Checking 2/3...
[TensorRT] WARNING: onnx2trt_utils.cpp:320: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
mini_code.py:52: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
[TensorRT] WARNING: Convolution + generic activation fusion is disable due to incompatible driver or nvrtc
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.4.2 but loaded cuBLAS/cuBLAS LT 11.2.1
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
[TensorRT] ERROR: 4: [pluginV2Builder.cpp::makeRunner::680] Error Code 4: Internal Error (Internal error: plugin node ScatterND_12 requires 36 bytes of scratch space, but only 0 is available. Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
)
Traceback (most recent call last):
  File "mini_code.py", line 55, in <module>
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```

**Comment by MHGL** [comment]
```python3
# init module
class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        ...

    def forward(self, x):
        y = x[:1] + 1
        return y
```
work well, is this a bug ?

**Comment by MHGL** [comment]
https://github.com/DeepVAC/deepvac/issues/122

**Comment by lisongze** [comment]
I met the same error:
`[TensorRT] ERROR: Internal error: plugin node ScatterND_1requires 400032 bytes of scratch space, but only 0 is available. Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1118) - OutOfMemory Error in checkPluginScratchSize: 0`

I also used `trtexec`, it came with some error from "LogStream" or invalid pointer error

**Comment by lisongze** [comment]
I solved this problem.

You build the engine with `builder.build_engine(network, config)`, which is build with config.
As the log said `Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig`, so you should set `max_workspace_size` for builder config, just add the line `config.max_workspace_size = 1 << 30` .

**Comment by MHGL** [comment]
> thank you for your reply, I tried this and it work well on tensorrt == 8.0.0.3
