### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator FakeTensorQuantFunction

### ISSUE THREAD

**Issue by talcs** [NVIDIA/TensorRT#3513]
## Description

Following block 19 in the [PTQ tutorial](https://github.com/NVIDIA/TensorRT/blob/main/quickstart/quantization_tutorial/qat-ptq-workflow.ipynb), I was trying to export the model to ONNX after the calibration.

Got this error:
```
File D:\Anaconda3\lib\site-packages\torch\onnx\__init__.py:350, in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
     74 r"""
     75 Exports a model into ONNX format. If ``model`` is not a
     76 :class:`torch.jit.ScriptModule` nor a :class:`torch.jit.ScriptFunction`, this runs
   (...)
    345     model to the file ``f`` even if this is raised.
    346 """
    348 from torch.onnx import utils
--> 350 return utils.export(
    351     model,
    352     args,
    353     f,
    354     export_params,
    355     verbose,
    356     training,
    357     input_names,
    358     output_names,
    359     operator_export_type,
    360     opset_version,
    361     do_constant_folding,
    362     dynamic_axes,
    363     keep_initializers_as_inputs,
    364     custom_opsets,
    365     export_modules_as_functions,
    366 )

File D:\Anaconda3\lib\site-packages\torch\onnx\utils.py:163, in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
    145 def export(
    146     model,
    147     args,
   (...)
    160     export_modules_as_functions=False,
    161 ):
--> 163     _export(
    164         model,
    165         args,
    166         f,
    167         export_params,
    168         verbose,
    169         training,
    170         input_names,
    171         output_names,
    172         operator_export_type=operator_export_type,
    173         opset_version=opset_version,
    174         do_constant_folding=do_constant_folding,
    175         dynamic_axes=dynamic_axes,
    176         keep_initializers_as_inputs=keep_initializers_as_inputs,
    177         custom_opsets=custom_opsets,
    178         export_modules_as_functions=export_modules_as_functions,
    179     )

File D:\Anaconda3\lib\site-packages\torch\onnx\utils.py:1110, in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, onnx_shape_inference, export_modules_as_functions)
   1101 params_dict = _C._jit_pass_onnx_deduplicate_initializers(  # type: ignore[assignment]
   1102     graph, params_dict, getattr(model, "training", False)  # type: ignore[arg-type]
   1103 )
   1104 if export_params:
   1105     (
   1106         proto,
   1107         export_map,
   1108         val_use_external_data_format,
   1109         node_names,
-> 1110     ) = graph._export_onnx(  # type: ignore[attr-defined]
   1111         params_dict,
   1112         opset_version,
   1113         dynamic_axes,
   1114         defer_weight_export,
   1115         operator_export_type,
   1116         not verbose,
   1117         val_keep_init_as_ip,
   1118         custom_opsets,
   1119         val_add_node_names,
   1120         model_file_location,
   1121         node_attr_to_name,
   1122     )
   1123 else:
   1124     (
   1125         proto,
   1126         export_map,
   (...)
   1140         node_attr_to_name,
   1141     )

RuntimeError: ONNX export failed: Couldn't export Python operator FakeTensorQuantFunction
```

## Environment

Torch version: 1.12.1+cu116
pytorch_quantization version: 2.1.3
Operating system: Windows 10

**Comment by talcs** [comment]
Migrating to Pytorch version `2.1.1+cu121` **solved the problem**. It forced me to install the `onnx` package - so it seems that the internal implementation of onnx export  has changed.

**Comment by ttyio** [comment]
Hi @talcs , also try: 

      with pytorch_quantization.enable_onnx_export():
             # enable_onnx_checker needs to be disabled. See notes below.
             torch.onnx.export(...)

we have latest document in https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/index.html#export-to-onnx, but this tutorial seems out of date, still use `use_fb_fake_quant`, will update it. thanks!

**Comment by talcs** [comment]
So is `with pytorch_quantization.enable_onnx_export()` replacing `quant_nn.TensorQuantizer.use_fb_fake_quant = True` ?

I used neither.. Is it possible that the ONNX model it created is not what `trtexec` expects?

**Comment by ttyio** [comment]
@talcs there should no issue for your newer torch version, we only have some sanity check when you added those code. Thanks!

**Comment by talcs** [comment]
I just got this error: `AttributeError: module 'pytorch_quantization' has no attribute 'enable_onnx_export'`

**Comment by Ray-Luo** [comment]
> I just got this error: `AttributeError: module 'pytorch_quantization' has no attribute 'enable_onnx_export'`

I have the same error

**Comment by ttyio** [comment]
@talcs @Ray-Luo , sorry for the delay response.
The `enable_onnx_export` is available in latest QAT version 2.2.1, can be installed via:

     pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com/ pytorch-quantization

**Comment by RuRo** [comment]
@ttyio can you clarify, which branch/tag/commit corresponds to version `2.2.1`? I can't use the prebuilt wheels and need to compile from source due to #3497.

The default branch (`release/8.6`) has pytorch_quantization version `2.1.3`. `main` and `master` also have older versions (`2.1.2` and `2.1.1` respectively). The `v9.2.0` tag also has version `2.1.3`.

The `release/9.2` branch (currently on commit 93b6044fc106b69bce6751f27aa9fc198b02bddc) does have version `2.2.1`, but it fails to build with some compiler errors in `src/tensor_quant_gpu.cu`.

**Comment by ttyio** [comment]
@RuRo  which container are you using when do the compilation, have you tried torch container like `nvcr.io/nvidia/pytorch:22.12-py3` ? thanks!

**Comment by RuRo** [comment]
@ttyio I am using a custom container based on the `nvidia/cuda` container with a bunch of extra stuff added. Unfortunately, I am unable to share the Dockerfile.

I was eventually able to build `release/9.2` (commit 93b6044fc106b69bce6751f27aa9fc198b02bddc) by reverting the changes to `tools/pytorch-quantization/src/tensor_quant_gpu.cu` that were introduced in commit f3cd7b6a093c0a98d12d9f413a3563b14d1258ce. Specifically:
<details>
<summary>revert_f3cd7b6_tensor_quant_gpu.diff</summary>

```diff
diff --git a/tools/pytorch-quantization/src/tensor_quant_gpu.cu b/tools/pytorch-quantization/src/tensor_quant_gpu.cu
index c56d978a..8be6ccda 100644
--- a/tools/pytorch-quantization/src/tensor_quant_gpu.cu
+++ b/tools/pytorch-quantization/src/tensor_quant_gpu.cu
@@ -25,16 +25,6 @@
 #define BLOCK_SIZE 128
 #define EPSILON (1. / (1<<24))  // Minimum representable of fp16
 
-#define AT_DISPATCH_CASE_FLOATING_TYPES(...)   \
-  AT_DISPATCH_CASE(at::ScalarType::Double, __VA_ARGS__)  \
-  AT_DISPATCH_CASE(at::ScalarType::Float, __VA_ARGS__)  \
-  AT_DISPATCH_CASE(at::ScalarType::Half, __VA_ARGS__)   \
-  AT_DISPATCH_CASE(at::ScalarType::BFloat16, __VA_ARGS__)
-
-#define AT_DISPATCH_FLOATING_TYPES(TYPE, NAME, ...) \
-  AT_DISPATCH_SWITCH(                                        \
-      TYPE, NAME, AT_DISPATCH_CASE_FLOATING_TYPES(__VA_ARGS__))
-
 __host__ __device__ float bits_to_bound(int num_bits, int is_unsigned) {
   float bound = (1 << (num_bits - 1 + int(is_unsigned))) - 1;
   return bound;
@@ -75,7 +65,7 @@ __global__ void fake_tensor_quant_kernel(const T* inputs, size_t n, T* outputs,
 void fake_tensor_quant_cuda_inplace(at::Tensor inputs, at::Tensor amax, int num_bits = 8,
                                     bool is_unsigned = false, bool narrow_range = true) {
   size_t numel = inputs.numel();
-  AT_DISPATCH_FLOATING_TYPES(
+  AT_DISPATCH_FLOATING_TYPES_AND_HALF(
       inputs.type().scalarType(), "fake_tensor_quant_cuda_inplace", [&] {
         fake_tensor_quant_kernel<<<numel / BLOCK_SIZE + 1, BLOCK_SIZE>>>(
             inputs.data_ptr<scalar_t>(), numel, inputs.data_ptr<scalar_t>(),
@@ -87,7 +77,7 @@ at::Tensor fake_tensor_quant_cuda(at::Tensor inputs, at::Tensor amax, int num_bi
                                   bool is_unsigned = false, bool narrow_range = true) {
   size_t numel = inputs.numel();
   auto outputs = torch::empty_like(inputs);
-  AT_DISPATCH_FLOATING_TYPES(inputs.type().scalarType(), "fake_tensor_quant_cuda", [&] {
+  AT_DISPATCH_FLOATING_TYPES_AND_HALF(inputs.type().scalarType(), "fake_tensor_quant_cuda", [&] {
     fake_tensor_quant_kernel<<<numel / BLOCK_SIZE + 1, BLOCK_SIZE>>>(
         inputs.data_ptr<scalar_t>(), numel, outputs.data_ptr<scalar_t>(),
         amax.to(at::ScalarType::Float).data_ptr<float>(), num_bits, is_unsigned);
@@ -127,33 +117,10 @@ at::Tensor fake_tensor_quant_with_axis_cuda(at::Tensor inputs, at::Tensor amax,
 
   int outer_size = inputs.stride(axis);
 
-  AT_DISPATCH_FLOATING_TYPES(inputs.type().scalarType(), "fake_tensor_quant_cuda_with_axis", [&] {
+  AT_DISPATCH_FLOATING_TYPES_AND_HALF(inputs.type().scalarType(), "fake_tensor_quant_cuda_with_axis", [&] {
     fake_tensor_quant_with_axis_cuda_kernel<<<numel / (BLOCK_SIZE * 4) + 1, BLOCK_SIZE>>>(
         inputs.data_ptr<scalar_t>(), numel, outputs.data_ptr<scalar_t>(),
         amax.to(at::ScalarType::Float).data_ptr<float>(), axis_size, outer_size, num_bits, is_unsigned);
   });
   return outputs;
 }
-
-#if CUDA_VERSION > 11070
-  #include <cuda_fp8.h>
-
-  template <typename T>
-  __global__ void fake_e4m3fy_kernel(const T* inputs, size_t n, T* outputs) {
-    int tid = blockIdx.x * blockDim.x + threadIdx.x;
-
-    for (int idx = 4 * tid; idx < 4 * (tid + 1) && idx < n; ++idx) {
-      outputs[idx] = static_cast<T>(static_cast<float>(static_cast<__nv_fp8_e4m3>(static_cast<float>(inputs[idx]))));
-    }
-  }
-
-  at::Tensor fake_e4m3fy_cuda(at::Tensor inputs) {
-    size_t numel = inputs.numel();
-    auto outputs = torch::empty_like(inputs);
-    AT_DISPATCH_FLOATING_TYPES(inputs.type().scalarType(), "fake_e4m3fy_cuda", [&] {
-      fake_e4m3fy_kernel<<<numel / (BLOCK_SIZE * 4) + 1, BLOCK_SIZE>>>(
-          inputs.data_ptr<scalar_t>(), numel, outputs.data_ptr<scalar_t>());
-    });
-    return outputs;
-  }
-#endif
```

</details>


After that I was able to successfully export the quantized model, however it didn't work with `trtexec` due to #3577. So now I am waiting on that issue.

**Comment by ttyio** [comment]
Thanks @RuRo , I will close this since this is WAR. 
For the https://github.com/NVIDIA/TensorRT/issues/3577, before we fix that, the WAR is to inline all the zero points in the Q/DQ.
We have not seen this `Identity(INT8) -> Q/DQ zero` point before, so it trigger some INT8 constant assertion in TRT. 

![image](https://github.com/NVIDIA/TensorRT/assets/365590/826346e5-6e8a-4819-ba4b-7b9e2643f31d)

Thanks!
