### ISSUE TITLE
“Error Code 2: Internal Error (Assertion y->type() == signature.operandType(1) failed.” failure of TensorRT 8.5.2 when running sam_decoder.onnx on GPU RTX 3060

### ISSUE THREAD

**Issue by anyingyi** [NVIDIA/TensorRT#2968]
## Description

I tried to transfer onnx file of sam to tensorRT for deployment, but it fails with the error below .

"""
[2023-05-15 15:36:25][info][trt_builder.cpp:474]:Compile FP32 Onnx Model 'D:/xiaowen/python/logs/sam/sam_vit_b_encoder.onnx'.
[2023-05-15 15:36:35][warn][trt_builder.cpp:33]:NVInfer: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[2023-05-15 15:36:36][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:736: While parsing node number 297 [Mod -> "onnx::Sub_211"]:
[2023-05-15 15:36:36][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:737: --- Begin node ---
[2023-05-15 15:36:36][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:738: input: "onnx::Mod_203"
input: "onnx::Mod_210"
output: "onnx::Sub_211"
name: "Mod_297"
op_type: "Mod"
attribute {
  name: "fmod"
  i: 0
  type: INT
}

[2023-05-15 15:36:36][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:739: --- End node ---
[2023-05-15 15:36:36][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:742: ERROR: TensorRT\onnx_parser\builtin_op_importers.cpp:4742 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[2023-05-15 15:36:36][error][trt_builder.cpp:519]:Can not parse OnnX file: D:/xiaowen/python/logs/sam/sam_vit_b_encoder.onnx
[2023-05-15 15:36:36][info][direct_sam.cpp:40]:Compile done
[2023-05-15 15:36:36][info][trt_builder.cpp:474]:Compile FP32 Onnx Model 'D:/xiaowen/python/logs/sam/sam_vit_b_decoder.onnx'.
[2023-05-15 15:36:38][warn][trt_builder.cpp:33]:NVInfer: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[2023-05-15 15:36:40][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:534: Found unsupported shape-tensor producing layer:Reciprocal_1095
[2023-05-15 15:36:40][warn][trt_builder.cpp:33]:NVInfer: Tensor DataType is determined at build time for tensors not marked as input or output.
[2023-05-15 15:36:40][warn][trt_builder.cpp:33]:NVInfer: Tensor DataType is determined at build time for tensors not marked as input or output.
[2023-05-15 15:36:40][error][trt_builder.cpp:30]:NVInfer: TensorRT\onnx_parser\ModelImporter.cpp:534: Found unsupported shape-tensor producing layer:Floor_1101
[2023-05-15 15:36:40][info][trt_builder.cpp:558]:Input shape is -1 x 256 x 64 x 64
[2023-05-15 15:36:40][info][trt_builder.cpp:559]:Set max batch size = 1
[2023-05-15 15:36:40][info][trt_builder.cpp:560]:Set max workspace size = 3072.00 MB
[2023-05-15 15:36:40][info][trt_builder.cpp:561]:Base device: [ID 0]<NVIDIA GeForce RTX 3060>[arch 8.6][GMEM 10.75 GB/12.00 GB]
[2023-05-15 15:36:40][info][trt_builder.cpp:564]:Network has 6 inputs:
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      0.[image_embeddings] shape is -1 x 256 x 64 x 64
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      1.[point_coords] shape is -1 x -1 x 2
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      2.[point_labels] shape is -1 x -1
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      3.[mask_input] shape is -1 x 1 x 256 x 256
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      4.[has_mask_input] shape is -1
[2023-05-15 15:36:40][info][trt_builder.cpp:570]:      5.[orig_im_size] shape is -1
[2023-05-15 15:36:40][info][trt_builder.cpp:576]:Network has 3 outputs:
[2023-05-15 15:36:41][error][trt_builder.cpp:30]:NVInfer: 2: [shapeContext.cpp::nvinfer1::builder::ShapeContext::op::1661] Error Code 2: Internal Error (Assertion y->type() == signature.operandType(1) failed. )
"""

## Environment

**TensorRT Version**:
8.5.2.2

**NVIDIA GPU**:
RTX 3060

**NVIDIA Driver Version**:
 Driver Version: 517.02

**CUDA Version**:
CUDA Version: 11.7

**CUDNN Version**:
8.6

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
no

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):
yes, run with onnxruntime is perfect.

```[tasklist]
### Tasks
```

**Comment by zerollzeng** [comment]
Weird, we support Mod operator but it fails, could you please provide a reproduce for this issue? Thanks!

FYI TRT supported onnx operators: https://github.com/onnx/onnx-tensorrt/blob/main/docs/operators.md

**Comment by anyingyi** [comment]
i share resource with google drive ->
https://drive.google.com/drive/folders/1Sbvh7nHlcqUjGb6H31PBhMxC4NrYDzxk?usp=sharing

**Comment by zerollzeng** [comment]
TRT 8.6.1. Looks like one of the input is shape tensor, modify it as int32 first.
```
[05/18/2023-10:18:57] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/18/2023-10:18:58] [E] Error[4]: [graphShapeAnalyzer.cpp::demandAndResolveInputTensor::1247] Error Code 4: Internal Error (orig_im_size: network input that is shape tensor must have type Int32)
[05/18/2023-10:18:58] [E] [TRT] ModelImporter.cpp:771: While parsing node number 1110 [Slice -> "onnx::Slice_1514"]:
[05/18/2023-10:18:58] [E] [TRT] ModelImporter.cpp:772: --- Begin node ---
[05/18/2023-10:18:58] [E] [TRT] ModelImporter.cpp:773: input: "onnx::Slice_1492"
input: "onnx::Slice_1617"
input: "onnx::Slice_1511"
input: "onnx::Slice_1618"
input: "onnx::Slice_1513"
output: "onnx::Slice_1514"
name: "Slice_1110"
op_type: "Slice"

[05/18/2023-10:18:58] [E] [TRT] ModelImporter.cpp:774: --- End node ---
[05/18/2023-10:18:58] [E] [TRT] ModelImporter.cpp:777: ERROR: ModelImporter.cpp:195 In function parseGraph:
[6] Invalid Node - Slice_1110
[graphShapeAnalyzer.cpp::demandAndResolveInputTensor::1247] Error Code 4: Internal Error (orig_im_size: network input that is shape tensor must have type Int32)
[05/18/2023-10:18:58] [E] Failed to parse onnx file
[05/18/2023-10:18:58] [I] Finished parsing network model. Parse time: 0.102368
[05/18/2023-10:18:58] [E] Parsing model failed
[05/18/2023-10:18:58] [E] Failed to create engine from model or file.
[05/18/2023-10:18:58] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8601] # trtexec --onnx=sam_vit_b_decoder.onnx
```
onnx runtime
```
[I] onnxrt-runner-N0-05/18/23-10:20:12
    ---- Inference Input(s) ----
    {image_embeddings [dtype=float32, shape=(1, 256, 64, 64)],
     point_coords [dtype=float32, shape=(1, 1, 2)],
     point_labels [dtype=float32, shape=(1, 1)],
     mask_input [dtype=float32, shape=(1, 1, 256, 256)],
     has_mask_input [dtype=float32, shape=(1,)],
     orig_im_size [dtype=float32, shape=(2,)]}
2023-05-18 10:20:15.128034360 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running Resize node. Name:'Resize_1131' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:289 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.

Traceback (most recent call last):
  File "/home/scratch.zeroz_sw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 21, in <module>
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 132, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 177, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/runner.py", line 73, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Resize node. Name:'Resize_1131' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:289 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.
```

**Comment by anyingyi** [comment]
i am confused, all the input of sam_decoder dtype is float32, none is INT64.

**Comment by anyingyi** [comment]
thank you, i change the type of "orig_im_size " to INT32 and it can convert successful with script ->
"trtexec --onnx=sam_vit_b_decoder_new.onnx --saveEngine=sam_vit_b_decoder.trt"
but failed with c++ code ->

```
if (!iLogger::exists(decoderTrt)) {
        TRT::compile(
            mode,
            1,
            decoderPath,
            decoderTrt
        );
        INFO("Compile done");
    }
```


another question is sam_encoder.onnx to .trt is still failed, here is the error information and model. ->
```
[05/22/2023-15:58:35] [I] [TRT] Searching for plugin: Mod, plugin_version: 1, plugin_namespace:
[05/22/2023-15:58:35] [E] [TRT] ModelImporter.cpp:773: While parsing node number 297 [Mod -> "onnx::Sub_211"]:
[05/22/2023-15:58:35] [E] [TRT] ModelImporter.cpp:774: --- Begin node ---
[05/22/2023-15:58:35] [E] [TRT] ModelImporter.cpp:775: input: "onnx::Mod_203"
input: "onnx::Mod_210"
output: "onnx::Sub_211"
name: "Mod_297"
op_type: "Mod"
attribute {
  name: "fmod"
  i: 0
  type: INT
}

[05/22/2023-15:58:35] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[05/22/2023-15:58:35] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[05/22/2023-15:58:35] [E] Failed to parse onnx file
[05/22/2023-15:58:35] [I] Finish parsing network model
[05/22/2023-15:58:35] [E] Parsing model failed
[05/22/2023-15:58:35] [E] Failed to create engine from model or file.
[05/22/2023-15:58:35] [E] Engine set up failed
```
```
https://drive.google.com/file/d/1VJeIgTVhVdfsjce9Xd9DYyy89t3FWqeF/view?usp=sharing
```

**Comment by zerollzeng** [comment]
Could you please share the sam_encoder.onnx here?

**Comment by anyingyi** [comment]
here is the sam_encoder.onnx in google drive ->
 https://drive.google.com/file/d/1tQ6-4V_xJ-Y_2gAGHAfgy2GiTSdkMuLV/view?usp=sharing

i am sorry for mistakenly give a wrong share above.

**Comment by zerollzeng** [comment]
Your model has dynamic shapes input, what's the input shape?

**Comment by anyingyi** [comment]
the input shape is 1x3x1024x1024

**Comment by zerollzeng** [comment]
Do constant folding and build with TRT 8.6.1:
```
polygraphy surgeon sanitize sam_vit_b_encoder.onnx --fold-constants -o sam_vit_b_encoder_folded.onnx

[05/27/2023-05:59:21] [I] === Performance summary ===
[05/27/2023-05:59:21] [I] Throughput: 7.06838 qps
[05/27/2023-05:59:21] [I] Latency: min = 133.301 ms, max = 140.229 ms, mean = 136.737 ms, median = 136.856 ms, percentile(90%) = 139.374 ms, percentile(95%) = 139.671 ms, percentile(99%) = 140.229 ms
[05/27/2023-05:59:21] [I] Enqueue Time: min = 1.01636 ms, max = 1.35168 ms, mean = 1.0534 ms, median = 1.04044 ms, percentile(90%) = 1.07022 ms, percentile(95%) = 1.07715 ms, percentile(99%) = 1.35168 ms
[05/27/2023-05:59:21] [I] H2D Latency: min = 0.575439 ms, max = 0.678528 ms, mean = 0.62104 ms, median = 0.622559 ms, percentile(90%) = 0.652344 ms, percentile(95%) = 0.666382 ms, percentile(99%) = 0.678528 ms
[05/27/2023-05:59:21] [I] GPU Compute Time: min = 132.483 ms, max = 139.418 ms, mean = 135.93 ms, median = 136.071 ms, percentile(90%) = 138.565 ms, percentile(95%) = 138.838 ms, percentile(99%) = 139.418 ms
[05/27/2023-05:59:21] [I] D2H Latency: min = 0.166992 ms, max = 0.194763 ms, mean = 0.186193 ms, median = 0.186768 ms, percentile(90%) = 0.189941 ms, percentile(95%) = 0.191772 ms, percentile(99%) = 0.194763 ms
[05/27/2023-05:59:21] [I] Total Host Walltime: 3.3954 s
[05/27/2023-05:59:21] [I] Total GPU Compute Time: 3.26233 s
[05/27/2023-05:59:21] [W] * GPU compute time is unstable, with coefficient of variance = 1.58917%.
[05/27/2023-05:59:21] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[05/27/2023-05:59:21] [I] Explanations of the performance metrics are printed in the verbose logs.
[05/27/2023-05:59:21] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --onnx=sam_vit_b_encoder_folded.onnx --shapes=model_input:1x3x1024x1024
```

**Comment by zerollzeng** [comment]
Can we close this? Thanks!

**Comment by anyingyi** [comment]
ok, i would close this now,thank you.

**Comment by anyingyi** [comment]
although the trt model is successful convert from onnx model, but the inference results is not correct. 
the output of sam decoder respectly as "masks", "iou_predictions", "low_res_masks", and the shape shoud be:
![image](https://github.com/NVIDIA/TensorRT/assets/29355122/6262f1de-fb2a-4af1-9791-17f8709d7589)

but with trt model infer, the shape of "masks", "iou_predictions", "low_res_masks" is :
![image](https://github.com/NVIDIA/TensorRT/assets/29355122/502edf5f-de7f-4a9b-8616-e79a12d990d6)

what's more, the final results get by trt infer is not the same as onnx infer.

**Comment by zerollzeng** [comment]
I try to reproduce with polygraphy, but looks like it's passed.
```
[I] trt-runner-N0-06/12/23-14:54:04
    ---- Inference Input(s) ----
    {model_input [dtype=float32, shape=(1, 3, 1024, 1024)]}
[I] trt-runner-N0-06/12/23-14:54:04
    ---- Inference Output(s) ----
    {model_output [dtype=float32, shape=(1, 256, 64, 64)]}
[I] trt-runner-N0-06/12/23-14:54:04     | Completed 1 iteration(s) in 173.3 ms | Average inference time: 173.3 ms.
[I] onnxrt-runner-N0-06/12/23-14:54:04  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[I] onnxrt-runner-N0-06/12/23-14:54:04
    ---- Inference Input(s) ----
    {model_input [dtype=float32, shape=(1, 3, 1024, 1024)]}
[I] onnxrt-runner-N0-06/12/23-14:54:04
    ---- Inference Output(s) ----
    {model_output [dtype=float32, shape=(1, 256, 64, 64)]}
[I] onnxrt-runner-N0-06/12/23-14:54:04  | Completed 1 iteration(s) in 1715 ms | Average inference time: 1715 ms.
[I] Accuracy Comparison | trt-runner-N0-06/12/23-14:54:04 vs. onnxrt-runner-N0-06/12/23-14:54:04
[I]     Comparing Output: 'model_output' (dtype=float32, shape=(1, 256, 64, 64)) with 'model_output' (dtype=float32, shape=(1, 256, 64, 64))
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[W]         onnxrt-runner-N0-06/12/23-14:54:04  | Output: model_output: Some values are 0. Will add a small epsilon quantity to these when computing relative difference. Note that this may cause some relative differences to be extremely high.
[I]         trt-runner-N0-06/12/23-14:54:04: model_output | Stats: mean=0.012985, std-dev=0.15556, var=0.024199, median=0.0018376, min=-0.84167 at (0, 175, 13, 52), max=0.8089 at (0, 241, 1, 56), avg-magnitude=0.098812
[I]         onnxrt-runner-N0-06/12/23-14:54:04: model_output | Stats: mean=0.012985, std-dev=0.15556, var=0.024199, median=0.0018376, min=-0.84167 at (0, 175, 13, 52), max=0.8089 at (0, 241, 1, 56), avg-magnitude=0.098812
[I]         Error Metrics: model_output
[I]             Minimum Required Tolerance: elemwise error | [abs=4.2021e-06] OR [rel=6.7466e+08] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=1.5224e-07, std-dev=1.7976e-07, var=3.2313e-14, median=8.9407e-08, min=0 at (0, 0, 0, 7), max=4.2021e-06 at (0, 175, 49, 20), avg-magnitude=1.5224e-07
[I]             Relative Difference | Stats: mean=643.41, std-dev=6.5885e+05, var=4.3408e+11, median=1.5058e-06, min=0 at (0, 0, 0, 7), max=6.7466e+08 at (0, 153, 60, 12), avg-magnitude=643.41
[I]         PASSED | Output: 'model_output' | Difference is within tolerance (rel=1e-05, abs=1e-05)
[I]     PASSED | All outputs matched | Outputs: ['model_output']
[I] Accuracy Summary | trt-runner-N0-06/12/23-14:54:04 vs. onnxrt-runner-N0-06/12/23-14:54:04 | Passed: 1/1 iterations | Pass Rate: 100.0%
[I] PASSED | Runtime: 60.635s | Command: /home/scratch.zeroz_sw/miniconda3/bin/polygraphy run sam_vit_b_encoder_folded.onnx --trt --onnxrt --trt-opt-shapes model_input:[1,3,1024,1024] --input-shapes model_input:[1,3,1024,1024]

```

**Comment by anyingyi** [comment]
the output shape of sam encoder is correct(i am not check the value between onnx output and trt output) (1, 256, 64, 64). 
the output shape of sam decoder is wrong. which should be (1,4,1024,1024), (1,4), (1,4,256,256) respectly, but trt output shape is   (1,4,256,256), (1,4), (1,4,1,1)

**Comment by zerollzeng** [comment]
> the output shape of sam decoder is wrong. which should be (1,4,1024,1024), (1,4), (1,4,256,256) respectly, but trt output shape is (1,4,256,256), (1,4), (1,4,1,1)

Could you please try polygraphy as I do?

**Comment by anyingyi** [comment]
here is the polygraphy results of sam_vit_b_decoder.onnx(i am sorry for not know polygraphy before.)
```
$ polygraphy run sam_vit_b_decoder.onnx --trt --onnxrt
[I] RUNNING | Command: D:\Program\ananconda3\envs\pytorch\Scripts\polygraphy run sam_vit_b_decoder.onnx --trt --onnxrt
[I] trt-runner-N0-06/16/23-15:31:51     | Activating and starting inference
[W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[W]     Input tensor: point_coords (dtype=DataType.FLOAT, shape=(1, -1, 2)) | No shapes provided; Will use shape: [1, 1, 2] for min/opt/max in profile.
[W]     This will cause the tensor to have a static shape. If this is incorrect, please set the range of shapes for this input tensor.
[W]     Input tensor: point_labels (dtype=DataType.FLOAT, shape=(1, -1)) | No shapes provided; Will use shape: [1, 1] for min/opt/max in profile.
[W]     Input shape-tensor: orig_im_size (dtype=DataType.INT32, shape=(2,)) | No values provided; Will use input values: (1, 1) for min/opt/max in profile.
[W]     This will cause the shape-tensor to have static values. If this is incorrect, please set the range of values for this input shape-tensor.
[I]     Configuring with profiles: [Profile().add('image_embeddings', min=[1, 256, 64, 64], opt=[1, 256, 64, 64], max=[1, 256, 64, 64]).add('point_coords', min=[1, 1, 2], opt=[1, 1, 2], max=[1, 1, 2]).add('point_labels', min=[1, 1], opt=[1, 1], max=[1, 1]).add('mask_input', min=[1, 1, 256, 256], opt=[1, 1, 256, 256], max=[1, 1, 256, 256]).add('has_mask_input', min=[1], opt=[1], max=[1]).add('orig_im_size', min=(1, 1), opt=(1, 1), max=(1, 1))]
[I] Building engine with configuration:
    Flags                  | []
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 12287.50 MiB, TACTIC_DRAM: 12287.50 MiB]
    Tactic Sources         | [CUBLAS, CUBLAS_LT, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[W] [RemoveDeadLayers] Input Tensor orig_im_size is unused or used only at compile-time, but is not being removed.
[I] Finished engine building in 81.588 seconds
[I] trt-runner-N0-06/16/23-15:31:51
    ---- Inference Input(s) ----
    {image_embeddings [dtype=float32, shape=(1, 256, 64, 64)],
     point_coords [dtype=float32, shape=(1, 1, 2)],
     point_labels [dtype=float32, shape=(1, 1)],
     mask_input [dtype=float32, shape=(1, 1, 256, 256)],
     has_mask_input [dtype=float32, shape=(1,)],
     orig_im_size [dtype=int32, shape=(2,)]}
[I] trt-runner-N0-06/16/23-15:31:51
    ---- Inference Output(s) ----
    {low_res_masks [dtype=float32, shape=(1, 4, 256, 256)],
     iou_predictions [dtype=float32, shape=(1, 4)],
     masks [dtype=float32, shape=(1, 4, 1, 1)]}
[I] trt-runner-N0-06/16/23-15:31:51     | Completed 1 iteration(s) in 5.99 ms | Average inference time: 5.99 ms.
[I] onnxrt-runner-N0-06/16/23-15:31:51  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[I] onnxrt-runner-N0-06/16/23-15:31:51
    ---- Inference Input(s) ----
    {image_embeddings [dtype=float32, shape=(1, 256, 64, 64)],
     point_coords [dtype=float32, shape=(1, 1, 2)],
     point_labels [dtype=float32, shape=(1, 1)],
     mask_input [dtype=float32, shape=(1, 1, 256, 256)],
     has_mask_input [dtype=float32, shape=(1,)],
     orig_im_size [dtype=int32, shape=(2,)]}
[I] onnxrt-runner-N0-06/16/23-15:31:51
    ---- Inference Output(s) ----
    {masks [dtype=float32, shape=(1, 4, 0, 1)],
     iou_predictions [dtype=float32, shape=(1, 4)],
     low_res_masks [dtype=float32, shape=(1, 4, 256, 256)]}
[I] onnxrt-runner-N0-06/16/23-15:31:51  | Completed 1 iteration(s) in 32.91 ms | Average inference time: 32.91 ms.
[I] Accuracy Comparison | trt-runner-N0-06/16/23-15:31:51 vs. onnxrt-runner-N0-06/16/23-15:31:51
[I]     Comparing Output: 'low_res_masks' (dtype=float32, shape=(1, 4, 256, 256)) with 'low_res_masks' (dtype=float32, shape=(1, 4, 256, 256))
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[I]         trt-runner-N0-06/16/23-15:31:51: low_res_masks | Stats: mean=-14.559, std-dev=11.799, var=139.22, median=-12.834, min=-162.77 at (0, 0, 140, 48), max=6.4406 at (0, 0, 245, 112), avg-magnitude=14.563
[I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (-163 , -146 ) |          1 |
                (-146 , -129 ) |          1 |
                (-129 , -112 ) |          3 |
                (-112 , -95.1) |         32 |
                (-95.1, -78.2) |        120 |
                (-78.2, -61.2) |        803 |
                (-61.2, -44.3) |       4655 | #
                (-44.3, -27.4) |      27823 | #########
                (-27.4, -10.5) |     121460 | ########################################
                (-10.5, 6.44 ) |     107246 | ###################################
[I]         onnxrt-runner-N0-06/16/23-15:31:51: low_res_masks | Stats: mean=-14.559, std-dev=11.799, var=139.22, median=-12.834, min=-162.77 at (0, 0, 140, 48), max=6.4405 at (0, 0, 245, 112), avg-magnitude=14.563
[I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (-163 , -146 ) |          1 |
                (-146 , -129 ) |          1 |
                (-129 , -112 ) |          3 |
                (-112 , -95.1) |         32 |
                (-95.1, -78.2) |        120 |
                (-78.2, -61.2) |        803 |
                (-61.2, -44.3) |       4655 | #
                (-44.3, -27.4) |      27825 | #########
                (-27.4, -10.5) |     121458 | ########################################
                (-10.5, 6.44 ) |     107246 | ###################################
[I]         Error Metrics: low_res_masks
[I]             Minimum Required Tolerance: elemwise error | [abs=0.0025024] OR [rel=1.1764] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=0.00018096, std-dev=0.00019414, var=3.7692e-08, median=0.0001049, min=0 at (0, 0, 13, 202), max=0.0025024 at (0, 3, 140, 48), avg-magnitude=0.00018096
[I]                 ---- Histogram ----
                    Bin Range            |  Num Elems | Visualization
                    (0       , 0.00025 ) |     189875 | ########################################
                    (0.00025 , 0.0005  ) |      52953 | ###########
                    (0.0005  , 0.000751) |      14603 | ###
                    (0.000751, 0.001   ) |       3619 |
                    (0.001   , 0.00125 ) |        852 |
                    (0.00125 , 0.0015  ) |        191 |
                    (0.0015  , 0.00175 ) |         40 |
                    (0.00175 , 0.002   ) |          7 |
                    (0.002   , 0.00225 ) |          2 |
                    (0.00225 , 0.0025  ) |          2 |
[I]             Relative Difference | Stats: mean=5.1783e-05, std-dev=0.0036202, var=1.3106e-05, median=1.1549e-05, min=0 at (0, 0, 13, 202), max=1.1764 at (0, 1, 23, 171), avg-magnitude=5.1783e-05
[I]                 ---- Histogram ----
                    Bin Range      |  Num Elems | Visualization
                    (0    , 0.118) |     262134 | ########################################
                    (0.118, 0.235) |          4 |
                    (0.235, 0.353) |          3 |
                    (0.353, 0.471) |          0 |
                    (0.471, 0.588) |          0 |
                    (0.588, 0.706) |          1 |
                    (0.706, 0.823) |          0 |
                    (0.823, 0.941) |          0 |
                    (0.941, 1.06 ) |          0 |
                    (1.06 , 1.18 ) |          2 |
[E]         FAILED | Output: 'low_res_masks' | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
[I]     Comparing Output: 'iou_predictions' (dtype=float32, shape=(1, 4)) with 'iou_predictions' (dtype=float32, shape=(1, 4))
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[I]         trt-runner-N0-06/16/23-15:31:51: iou_predictions | Stats: mean=0.71104, std-dev=0.16555, var=0.027407, median=0.74705, min=0.46231 at (0, 1), max=0.88776 at (0, 3), avg-magnitude=0.71104
[I]         onnxrt-runner-N0-06/16/23-15:31:51: iou_predictions | Stats: mean=0.71104, std-dev=0.16555, var=0.027407, median=0.74705, min=0.46231 at (0, 1), max=0.88777 at (0, 3), avg-magnitude=0.71104
[I]         Error Metrics: iou_predictions
[I]             Minimum Required Tolerance: elemwise error | [abs=3.3379e-06] OR [rel=4.019e-06] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=1.8775e-06, std-dev=9.4384e-07, var=8.9084e-13, median=1.6689e-06, min=8.3447e-07 at (0, 1), max=3.3379e-06 at (0, 0), avg-magnitude=1.8775e-06
[I]             Relative Difference | Stats: mean=2.5888e-06, std-dev=1.0139e-06, var=1.028e-12, median=2.4295e-06, min=1.4771e-06 at (0, 3), max=4.019e-06 at (0, 0), avg-magnitude=2.5888e-06
[I]         PASSED | Output: 'iou_predictions' | Difference is within tolerance (rel=1e-05, abs=1e-05)
[I]     Comparing Output: 'masks' (dtype=float32, shape=(1, 4, 1, 1)) with 'masks' (dtype=float32, shape=(1, 4, 0, 1))
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[E]         Will not compare outputs of different shapes. Note: Output shapes are (1, 4, 1, 1) and (1, 4, 0, 1).
[E]         Note: Use --no-shape-check or set check_shapes=False to attempt to compare values anyway.
[E]         FAILED | Output: 'masks' | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
[E]     FAILED | Mismatched outputs: ['low_res_masks', 'masks']
[E] Accuracy Summary | trt-runner-N0-06/16/23-15:31:51 vs. onnxrt-runner-N0-06/16/23-15:31:51 | Passed: 0/1 iterations | Pass Rate: 0.0%
[E] FAILED | Runtime: 87.647s | Command: D:\Program\ananconda3\envs\pytorch\Scripts\polygraphy run sam_vit_b_decoder.onnx --trt --onnxrt
```

**Comment by zerollzeng** [comment]
> (0.00225 , 0.0025  ) |          2 |

The output range is [-163, 6.44], this looks good to me.

**Comment by anyingyi** [comment]
do you run with sam_vit_b_encoder_folded.onnx? this works good for me too. 
but sam_vit_b_decoder.onnx is wrong.

**Comment by chaitanyakrishna1248** [comment]
> . Looks like one of the input is shape tensor, modify it as int32 first.

Hey, may I know where did you change this? Is it in the inputs before giving it to tensorrt or in the model itself?
