### ISSUE TITLE
incompatible types Int64 and Int32

### ISSUE THREAD

**Issue by antithing** [NVIDIA/TensorRT#4268]
I am trying to build an engine using TensorRT 10 and the `superpoint_v1_sim_int32.onnx` model.

I get:

```
[12/04/2024-13:22:39] [E] [TRT] ModelImporter.cpp:948: --- End node ---
[12/04/2024-13:22:39] [E] [TRT] ModelImporter.cpp:951: ERROR: ModelImporter.cpp:197 In function parseNode:
[6] Invalid Node - Concat_43
ITensor::getDimensions: Error Code 4: API Usage Error (Concat_43: concat input tensors 0 and 3 have incompatible types Int64 and Int32)
```

This was working well with TensorRT 8.6, what do I need to do to build the engine in TRT 10?

Thanks!

**Comment by asfiyab-nvidia** [comment]
Can you please share the ONNX model and the command/script you're using to build the engine?

**Comment by lix19937** [comment]
incompatible types， onnx-trt has check the two inputs's type.

**Comment by LeoZDong** [comment]
@antithing Upon inspecting your provided model, it seems to be an issue with the model itself. 

The error is the following:
```
Error (Concat_43: concat input tensors 0 and 3 have incompatible types Int64 and Int32)
```
The violating op `Concat_43` takes in 5 inputs, where input tensor 0 is `name: 67` and input tensor 3 is `name: 142`. `name: 67` is a variable input and inferred to be type `int64` (it comes from the output of the `Shape_30` op), while `name: 142` is an [initializer](https://onnx.ai/onnx/intro/concepts.html#input-output-node-initializer-attributes) with a fixed value of `8` and type `int32`. 

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/8987c745-9738-4ab5-9f07-c7b0adfea9dc" />

ONNX requires all inputs to `Concat` to be of the same type (see [here](https://github.com/onnx/onnx/blob/main/docs/Operators.md#inputs-1---), where the input type is a type variable `T` instead of a type union), so it's not actually a valid operation. 

In fact, `onnxruntime` also rejects the model. Likely due to a different graph traversal order than TensorRT, it complains about a different violating op `Mult_49`, but the error is the same.

Script:
```
import onnxruntime as ort
import numpy as np

session = ort.InferenceSession("superpoint_v1_sim_int32.onnx")

# Get input details
input_name = session.get_inputs()[0].name
input_shape = session.get_inputs()[0].shape
input_type = session.get_inputs()[0].type

print(f"Input Name: {input_name}")
print(f"Input Shape: {input_shape}")
print(f"Input Type: {input_type}")

# Generate dummy input
# Note: If input shape contains None or dynamic dimensions, adjust appropriately
dummy_input = np.random.rand(*[dim if dim is not None else 1 for dim in input_shape]).astype(np.float32)

# Run inference
outputs = session.run(None, {input_name: dummy_input})
```
Error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from superpoint_v1_sim_int32.onnx failed:Type Error: Type parameter (T) of Optype (Mul) bound to different types (tensor(int64) and tensor(int32) in node (Mul_49).
```

To resolve this, you could either change all the initializers to `int64` or add explicit cast operators in your model.
